apiVersion: v1
kind: Service
metadata:
    name: minigoodreads-be-svc
spec:
    type: ClusterIP
    selector:
        app: minigoodreads-be
    ports:
        - name: minigoodreads-be-port
          port: 8081
          targetPort: 8081
          protocol: TCP
