apiVersion: v1
kind: Service
metadata:
    name: minigoodreads-db-svc
spec:
    type: ClusterIP
    selector:
        app: minigoodreads-db
    ports:
        - port: 3306
          targetPort: 3306
          protocol: TCP
